"""empty message

Revision ID: 009c0a57ef47
Revises: 5887ec54c578
Create Date: 2022-05-15 23:37:03.437340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '009c0a57ef47'
down_revision = '5887ec54c578'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cart_customer_id_fkey', 'cart', type_='foreignkey')
    op.create_foreign_key(None, 'cart', 'customer', ['customer_id'], ['id'])
    op.add_column('customer', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('customer', 'customer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('customer_id', sa.INTEGER(), server_default=sa.text("nextval('customer_customer_id_seq'::regclass)"), autoincrement=True, nullable=False))
    op.drop_column('customer', 'id')
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.create_foreign_key('cart_customer_id_fkey', 'cart', 'customer', ['customer_id'], ['customer_id'])
    # ### end Alembic commands ###
